services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bravo
    ports:
      - 54321:5432
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data:
